# Generated by cucumber-sinatra. (Mon Mar 21 09:16:02 -0400 2011)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'profbingo.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = ProfBingoApp

class ProfBingoAppWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ProfBingoAppWorld.new
end
